<?php

namespace App\Models\MySQL\User;

use Illuminate\Database\Eloquent\Model;


class PrivateUser extends Model {
    protected $connection = 'localMySQL';
    
    protected $table = 'privateUsers';

    protected $primaryKey = 'id';

    protected $fillable = [
        'id', // int
        'username', // string (max 30, required)
        'fullName', // string (max 50, required)
        'salt', // string (max 50, required)
        'hashedPassword', // string (max 50, required)
        'created', // datetime (autogenerated)
        'isVerified', // bool (required)

        'encryptedContactInfo', // byte[] (required)
        'contactInfoEncryptionIv', // byte[] (required)
        'contactInfoEncryptionAuthTag', // byte[] (required)

        'encryptedAccountBasedIn', // byte[] (optional)
        'accountBasedInEncryptionIv', // byte[] (optional)
        'accountBasedInEncryptionAuthTag', // byte[] (optional)

        'encryptedDateOfBirth', // byte[] (required)
        'dateOfBirthEncryptionIv', // byte[] (required)
        'dateOfBirthEncryptionAuthTag', // byte[] (required)

        'encryptedDataEncryptionKey' // byte[] (required)
    ];
}
